"""
generate_docs_pdf.py
--------------------
One-off script that generates backend_documentation.pdf — a full walkthrough of
the backend architecture and request workflow for the syllabus chatbot.

Usage:  ./venv/Scripts/python.exe generate_docs_pdf.py
Output: backend_documentation.pdf (same folder)
"""

from fpdf import FPDF

OUT_FILE = "backend_documentation.pdf"

ACCENT = (13, 71, 161)      # deep blue
LIGHT = (227, 236, 250)     # light blue row fill
CODE_BG = (245, 245, 245)
GREY = (90, 90, 90)


def s(text: str) -> str:
    """Sanitize text to latin-1 so fpdf2 core fonts never raise."""
    replacements = {
        "\u2192": "->", "\u2190": "<-", "\u2713": "[OK]", "\u2717": "[X]",
        "\u2014": "--", "\u2013": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u00d7": "x",
        "\u2265": ">=", "\u2264": "<=", "\u2022": "-",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "replace").decode("latin-1")


class Doc(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_y(10)
        self.set_x(self.l_margin)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GREY)
        half = (self.w - self.l_margin - self.r_margin) / 2
        self.cell(half, 6, s("Backend Documentation - Syllabus Chatbot"), align="L")
        self.cell(half, 6, f"Page {self.page_no()}", align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-14)
        self.set_draw_color(200, 200, 200)
        self.line(15, self.get_y(), self.w - 15, self.get_y())
        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(*GREY)
        self.cell(0, 8, s("Generated by generate_docs_pdf.py - backend_langchain project"), align="C")

    # ── building blocks ──────────────────────────────────────────────────
    def h1(self, num, title):
        if self.get_y() > 240:
            self.add_page()
        self.ln(4)
        self.set_fill_color(*ACCENT)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, s(f"  {num}. {title}"), fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

    def h2(self, title):
        if self.get_y() > 255:
            self.add_page()
        self.set_text_color(*ACCENT)
        self.set_font("Helvetica", "B", 11.5)
        self.cell(0, 7, s(title), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def para(self, text, size=10):
        self.set_text_color(30, 30, 30)
        self.set_font("Helvetica", "", size)
        self.multi_cell(0, 5.2, s(text))
        self.ln(1.5)

    def bullets(self, items):
        for it in items:
            if self.get_y() > 270:
                self.add_page()
            self.set_x(self.l_margin)
            self.set_text_color(*ACCENT)
            self.set_font("Helvetica", "B", 10)
            self.cell(6, 5.2, "-", align="C")
            self.set_text_color(30, 30, 30)
            self.set_font("Helvetica", "", 10)
            self.multi_cell(0, 5.2, s(it))
        self.ln(1.5)

    def code(self, lines):
        self.set_fill_color(*CODE_BG)
        self.set_draw_color(210, 210, 210)
        self.set_font("Courier", "", 9)
        self.set_text_color(40, 40, 40)
        lh = 4.6
        block_h = len(lines) * lh + 4
        if self.get_y() + block_h > 275:
            self.add_page()
        x, y = self.get_x(), self.get_y()
        self.rect(x, y, self.w - x - 15, block_h, "DF")
        self.set_xy(x + 2, y + 2)
        for line in lines:
            self.cell(self.w - x - 19, lh, s(line), new_x="LMARGIN", new_y="NEXT")
            self.set_x(x + 2)
        self.set_xy(x, y + block_h + 3)

    def table(self, headers, rows, widths):
        if self.get_y() > 230:
            self.add_page()
        self.set_font("Helvetica", "B", 9)
        self.set_fill_color(*ACCENT)
        self.set_text_color(255, 255, 255)
        for h, w in zip(headers, widths):
            self.cell(w, 7, s(h), border=1, fill=True, align="C")
        self.ln()
        self.set_font("Helvetica", "", 8.7)
        fill = False
        for row in rows:
            heights = []
            for cell, w in zip(row, widths):
                n_lines = max(1, int(len(s(cell)) / (w / 1.75)) + 1)
                heights.append(n_lines * 4.8 + 2)
            rh = max(heights)
            if self.get_y() + rh > 278:
                self.add_page()
                self.set_font("Helvetica", "B", 9)
                self.set_fill_color(*ACCENT)
                self.set_text_color(255, 255, 255)
                for h, w in zip(headers, widths):
                    self.cell(w, 7, s(h), border=1, fill=True, align="C")
                self.ln()
                self.set_font("Helvetica", "", 8.7)
            y0 = self.get_y()
            x0 = self.get_x()
            fill = not fill
            self.set_fill_color(*(LIGHT if fill else (255, 255, 255)))
            self.set_text_color(30, 30, 30)
            for cell, w in zip(row, widths):
                x = self.get_x()
                self.rect(x, y0, w, rh, "D")
                self.set_xy(x + 1, y0 + 1)
                self.multi_cell(w - 2, 4.8, s(cell))
                self.set_xy(x + w, y0)
            self.set_xy(x0, y0 + rh)
        self.ln(3)


def build():
    pdf = Doc("P", "mm", "A4")
    pdf.set_margins(15, 15, 15)
    pdf.set_auto_page_break(True, margin=18)
    pdf.add_page()

    # ── cover ────────────────────────────────────────────────────────────
    pdf.ln(60)
    pdf.set_text_color(*ACCENT)
    pdf.set_font("Helvetica", "B", 26)
    pdf.cell(0, 14, "Backend Documentation", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 10, s("Syllabus Chatbot - FastAPI + LangChain Agent Architecture"),
             align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, s("Stack: Python | FastAPI | LangChain | MongoDB Atlas | Mistral + Gemini | GitHub MCP"),
             align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(20)
    pdf.set_draw_color(*ACCENT)
    pdf.line(70, pdf.get_y(), 140, pdf.get_y())

    # ── 1. overview ──────────────────────────────────────────────────────
    pdf.add_page()
    pdf.h1(1, "Overview")
    pdf.para(
        "The backend is an AI chatbot service for an ECE department. It answers questions about "
        "the college syllabus (from stored course PDFs), calculates CGPA, performs live web "
        "searches, and operates the user's GitHub account (repos, issues, pull requests, files)."
    )
    pdf.h2("How it works in one sentence")
    pdf.para(
        "A question arrives at one REST endpoint, a two-layer router decides what kind of "
        "question it is, binds only the relevant tools to an LLM, and an agent loop executes "
        "the LLM's chosen tools until it can stream a final answer back."
    )
    pdf.h2("Key components")
    pdf.bullets([
        "FastAPI server (uvicorn) - HTTP layer, CORS, health check",
        "Hybrid router - regex first (free/fast), Gemini Flash LLM only when ambiguous",
        "Agent loop - up to 4 rounds of LLM tool-calling per question",
        "Local tools - CGPA math, syllabus RAG search, Tavily web search",
        "GitHub MCP client - 32 remote tools over one authenticated connection",
        "MongoDB - stores embedded syllabus chunks (vector search) and chat history",
    ])

    # ── 2. folder structure ──────────────────────────────────────────────
    pdf.h1(2, "Folder Structure")
    pdf.code([
        "backend_langchain/",
        "|-- server.py               Entry point: uvicorn on 127.0.0.1:8000 (auto-reload)",
        "|-- .env                    Secrets: API keys, GitHub PAT, MongoDB URL",
        "|-- requirements.txt        Dependencies",
        "`-- app/",
        "    |-- main.py             FastAPI app: startup sequence, CORS, /health",
        "    |-- core/config.py      Reads .env ONCE into global `settings` object",
        "    |-- routes/llm.py       POST /chatbot - the ONLY chat endpoint",
        "    |-- auth/",
        "    |   |-- clerk.py        Verifies Clerk JWT tokens (login security)",
        "    |   `-- dependencies.py get_current_user - blocks unauthenticated calls",
        "    |-- ai/",
        "    |   |-- router.py       Decides WHAT the question is about (intent)",
        "    |   `-- chat_service.py The brain: runs the whole agent pipeline",
        "    |-- tools/",
        "    |   |-- __init__.py     Tool registry: merges local + GitHub tools",
        "    |   |-- cgpa_tool.py    calculate_cgpa (local math)",
        "    |   |-- rag_tool.py     syllabus_rag_search (searches course PDFs)",
        "    |   `-- tavily_tool.py  web_search_tool (live web search)",
        "    |-- services/mcp_client.py  GitHub MCP connection (32 tools)",
        "    |-- rag/                One-time setup: PDFs -> chunks -> embeddings -> Mongo",
        "    `-- db/mongodb.py       Async MongoDB connection (motor)",
    ])
    pdf.para(
        "Supporting folders: venv/ (Python environment), outputs/ (generated files served "
        "statically), uploads/, plus log files server.log and server.err.log."
    )

    # ── 3. startup workflow ──────────────────────────────────────────────
    pdf.h1(3, "Startup Workflow")
    pdf.para(
        "Triggered by uvicorn loading app.main:app. The lifespan context manager in main.py "
        "runs the sequence below before the server accepts requests."
    )
    pdf.table(
        ["Step", "Component", "What happens"],
        [
            ["1", "server.py", "uvicorn starts app.main:app on port 8000 with reload=True"],
            ["2", "main.py lifespan", "connect_to_mongo() opens the async Motor client"],
            ["3", "mcp_client.connect()", "Connects to https://api.githubcopilot.com/mcp/ using GITHUB_API_KEY as Bearer token. Retries 3 times with exponential backoff (2s, 4s, 8s)"],
            ["4", "MCP handshake", "Fetches all tool schemas from GitHub, keeps the 32 essential ones (search_repositories, get_file_contents, issues, PRs, commits...)"],
            ["5", "invalidate_tool_cache()", "Clears cached tool registries so they rebuild including MCP tools"],
            ["6", "Ready", "GET /health reports {mcp_connected, mcp_tools_count}"],
        ],
        [12, 38, 130],
    )
    pdf.h2("Failure handling")
    pdf.bullets([
        "If all 3 startup attempts fail, the server still boots - GitHub tools stay empty.",
        "ensure_connected() performs a lazy reconnect on the next GitHub query (throttled to once per 30s after failures; successes reset the throttle).",
        "A lock serializes concurrent reconnect attempts so parallel chats cannot stampede the endpoint.",
    ])

    # ── 4. request workflow ──────────────────────────────────────────────
    pdf.h1(4, "Request Workflow (POST /chatbot)")
    pdf.para(
        "Example query used throughout this section: 'give readme file of Instagram-clone "
        "project in my github'."
    )
    pdf.table(
        ["Step", "File", "What happens"],
        [
            ["1. Auth", "routes/llm.py + auth/", "Frontend POSTs JSON {user_prompt, ...} with a Clerk JWT. Depends(get_current_user) verifies the token against Clerk's JWKS URL before anything runs."],
            ["2. Setup", "chat_service.py", "ChatService created with prompt + conversation history. Initializes three LLMs: Mistral Small (primary), gemini-flash-latest (fallback), Gemini Flash temperature=0 (router)."],
            ["3. Route L1", "router.py", "Regex patterns score every intent (greeting, cgpa, syllabus, web_search, github). Score >= 2 routes directly; score 1 or 0 goes to Layer 2. Example matches 'github' 3x -> high confidence github."],
            ["4. Route L2", "router.py", "Only for ambiguous queries: Gemini Flash re-classifies using the last 6 history messages and picks intent + tool names as JSON."],
            ["5. Tool binding", "chat_service.py", "Intent selects a tool subset. GitHub intent binds ONLY the 32 MCP tools (local tools excluded to save tokens). bind_tools(..., tool_choice='auto')."],
            ["6. Guard", "chat_service.py", "GitHub intent but zero MCP tools? Tries mcp_client.ensure_connected() (lazy reconnect) before giving up with a clear error message."],
            ["7. Agent loop", "chat_service.py", "Up to MAX_TOOL_ROUNDS=4: invoke LLM -> if tool_calls present, execute them concurrently (asyncio.gather), append ToolMessages, loop. Otherwise treat response as final answer."],
            ["8. Streaming", "routes/llm.py", "Final answer streams token-by-token to the frontend as a StreamingResponse."],
        ],
        [24, 30, 126],
    )
    pdf.h2("Worked example - tool call chain")
    pdf.code([
        "Round 1: get_me()",
        "         -> username: priyadharshiniannadurai413-dev",
        "Round 2: search_repositories(query='user:<username> instagram clone in:name')",
        "         -> repo found: Instagram-clone",
        "Round 3: get_file_contents(owner=..., repo='Instagram-clone', path='README.md')",
        "         -> README content returned",
        "Final:   LLM formats and streams the README to the user",
    ])

    # ── 5. intent routing ────────────────────────────────────────────────
    pdf.h1(5, "Intent Routing Details")
    pdf.h2("Layer 1 regex triggers (router.py)")
    pdf.table(
        ["Intent", "Priority", "Example keywords matched"],
        [
            ["greeting", "2", "hi, hello, thanks, who are you (whole-message match only)"],
            ["cgpa", "5", "calculate, cgpa, gpa, sgpa, grade, semester gpa"],
            ["syllabus", "4", "syllabus, subject, unit, credits, semester, lab, cbc, 22XXnnn codes"],
            ["web_search", "3", "latest, placement, news, gate, salary, company, 2024-2026"],
            ["github", "10", "github, repo(sitory), issue, PR, commit, branch, merge, fork, clone, push, pull, code, readme, license, gist, milestone, starred"],
        ],
        [26, 16, 138],
    )
    pdf.para(
        "Ties are broken by priority - github wins because its keywords often collide with "
        "other intents (e.g. 'code', 'branch' can appear in academic questions)."
    )
    pdf.h2("Confidence rules")
    pdf.bullets([
        "score >= 2: high confidence - route immediately, no extra LLM cost.",
        "score == 1: low confidence - Gemini Flash router refines using conversation history.",
        "score == 0: ambiguous - LLM router decides between syllabus/web_search/etc.",
        "Greeting short-circuits instantly with a canned reply - zero LLM calls.",
    ])

    # ── 6. tools reference ───────────────────────────────────────────────
    pdf.h1(6, "Tools Reference")
    pdf.h2("Local tools (tools/ folder)")
    pdf.table(
        ["Tool", "Purpose", "Bound by intents"],
        [
            ["calculate_cgpa", "CGPA/GPA arithmetic from semester GPAs", "cgpa"],
            ["syllabus_rag_search", "Vector search over embedded course PDFs in MongoDB", "syllabus, ambiguous"],
            ["web_search_tool", "Tavily API live web search", "web_search, ambiguous"],
        ],
        [42, 84, 54],
    )
    pdf.h2("GitHub MCP tools (32, grouped)")
    pdf.table(
        ["Group", "Tools"],
        [
            ["Repos (7)", "search_repositories, create_repository, fork_repository, get_file_contents, create_or_update_file, delete_file, push_files"],
            ["Branches (2)", "list_branches, create_branch"],
            ["Commits (3)", "list_commits, get_commit, search_commits"],
            ["Issues (8)", "list_issues, issue_read, issue_write, add_issue_comment, search_issues, list_issue_fields, list_issue_types, sub_issue_write"],
            ["Pull Requests (10)", "list_pull_requests, pull_request_read, create_pull_request, update_pull_request, update_pull_request_branch, merge_pull_request, pull_request_review_write, add_reply_to_pull_request_comment, request_copilot_review, search_pull_requests"],
            ["Search + User (2)", "search_code, get_me"],
        ],
        [36, 144],
    )
    pdf.para(
        "tools/__init__.py merges local + MCP tools into cached registries "
        "(get_all_tools, get_tool_registry, get_mcp_tool_registry). Any MCP change calls "
        "invalidate_tool_cache() so registries rebuild on next access."
    )

    # ── 7. github resolution flow ────────────────────────────────────────
    pdf.h1(7, "Natural-Language GitHub Resolution")
    pdf.para(
        "Users rarely paste repo links - they say 'readme of my Instagram-clone project'. "
        "The system prompt (_SYSTEM_PROMPT in chat_service.py) teaches the LLM a mandatory "
        "workflow so it never guesses owner/repo names:"
    )
    pdf.code([
        "User mentions repo WITHOUT owner/link?",
        "  1. get_me()                      -> learn authenticated username (owner)",
        "  2. search_repositories(keywords) -> fuzzy-find candidate repos",
        "  3a. exactly ONE match            -> use full_name for the real request",
        "  3b. MULTIPLE matches             -> list them, ask user to choose",
        "  3c. NO match                     -> tell user repo not found",
        "",
        "Full URL given (github.com/owner/repo)?",
        "  -> extract owner+repo directly, skip steps 1-2",
        "",
        "NEVER invent owner or repo names.",
    ])
    pdf.para(
        "Router support: the github regex also fires on readme/license/gist/milestone/"
        "starred, so questions like 'show the README of my portfolio' route correctly even "
        "without the word 'github'."
    )

    # ── 8. recent fixes ──────────────────────────────────────────────────
    pdf.h1(8, "Recent Fixes & Reliability Notes")
    pdf.table(
        ["Fix", "Problem before", "Solution"],
        [
            ["MCP retry + lazy reconnect", "One failed connection at startup killed GitHub tools until manual restart", "connect() retries 3x with exponential backoff; ensure_connected() lazily reconnects on demand, throttled after failures, concurrency-safe via asyncio.Lock"],
            ["Repo resolution workflow", "Questions without explicit repo links failed or hallucinated owners", "System-prompt workflow: get_me -> search_repositories -> act (section 7)"],
            ["Fallback model retired", "gemini-1.5-flash returned 404 (model retired), so Mistral rate-limits produced 'technical difficulties' with no safety net", "Switched fallback to gemini-flash-latest - a version-less alias that always resolves to Google's current flash model"],
            ["Router keyword gaps", "Queries like 'show README of X' missed the github intent", "Added readme, license, gist, milestone, starred to the Layer-1 regex and LLM-router rules"],
        ],
        [34, 62, 84],
    )
    pdf.h2("Operational notes")
    pdf.bullets([
        "Rate limits: Mistral free tier throttles bursts; the Gemini fallback absorbs overflow automatically.",
        "Token economy: GitHub intent binds only MCP tools (~12k tokens instead of ~28k); essential-tools filter drops non-core schemas.",
        "Security: rotate the GitHub PAT if it was ever exposed; .env is loaded once at import time - restart after changing it.",
        "Health probe: GET /health returns mcp_connected and mcp_tools_count for quick diagnostics.",
    ])

    pdf.output(OUT_FILE)
    print(f"OK - wrote {OUT_FILE}")


if __name__ == "__main__":
    build()
